Remove duplicate CI test
The clang-tidy test was running twice.

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -27,6 +27,11 @@ jobs:
         with:
           style: file
           tidy-checks: ""
+      - name: Fail fast?!
+        if: steps.linter.outputs.checks-failed > 0
+        run: |
+          echo "Some files failed the linting checks!"
+          exit 1
 
   test:
     runs-on: ${{ matrix.image }}
@@ -40,20 +45,6 @@ jobs:
             image: ubuntu-latest
     steps:
       - uses: actions/checkout@v2
-
-      - name: Run clang-tidy
-        uses: shenxianpeng/cpp-linter-action@master
-        id: linter
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-        with:
-          style: file
-          tidy-checks: ""
-      - name: Fail fast?!
-        if: steps.linter.outputs.checks-failed > 0
-        run: |
-          echo "Some files failed the linting checks!"
-          exit 1
 
       - name: Set up Python ${{ matrix.python-version }}
         uses: actions/setup-python@v2
